### ISSUE TITLE
BaseSystem.chunklist

### ISSUE THREAD

**Issue by ryan628** [luffy9412/OpenCoreE480#2]
下载的时候报没权限

**Comment by UnlimitedBurst** [comment]
> 下载的时候报没权限
能贴一下完整的报错日志吗？
我刚刚用python脚本下载了最新版本的macOS系统引导镜像没发现有权限报错

![image](https://user-images.githubusercontent.com/16608185/102883314-ca96fb00-448a-11eb-9c2b-b3424f34b721.png)

**Comment by ryan628** [comment]
我找到原因了 公司的网下载有限制,下载50M之后断网了2分钟 造成后续问题,用热点就可以了

**Comment by UnlimitedBurst** [comment]
> 我找到原因了 公司的网下载有限制,下载50M之后断网了2分钟 造成后续问题,用热点就可以了

如果是网络异常那不应该会抛出没有权限的异常，一般会说是连接超时之类的，看了一下脚本源代码也没有自定义异常跟权限相关感觉有点奇怪，不过能下载下来就好，如果后续安装还有其他问题欢迎一起讨论。
